[project]
name = "code-advent"
version = "0.1.0"
description = "Advent of Code - 2024"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.1",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "polars>=1.35.2",
]
